import os, yaml, json, pathlib

def sanitize(s):
    return s.replace(' ', '-').lower()

def build_gumroad(data, outdir):
    # Minimal Gumroad JSON draft
    payload = {
        "name": data["title"],
        "description": data["description_md"],
        "price": int(round(float(data["price_usd"]) * 100)),  # cents
        "custom_permalink": sanitize(data["sku"]),
        "tag_names": data.get("keywords", []),
    }
    os.makedirs(outdir, exist_ok=True)
    with open(os.path.join(outdir, f"{data['sku']}.gumroad.json"), "w") as f:
        json.dump(payload, f, indent=2)

def build_etsy(data, outdir):
    # Minimal Etsy JSON draft (CSV import varies by shop; JSON kept for review)
    payload = {
        "title": data["title"],
        "description": data["description_md"],
        "price": float(data["price_usd"]),
        "who_made": "i_did",
        "is_supply": False,
        "when_made": "made_to_order",
        "tags": data.get("keywords", []),
        "taxonomy_id_note": "Set correct taxonomy in UI",
    }
    os.makedirs(outdir, exist_ok=True)
    with open(os.path.join(outdir, f\"{data['sku']}.etsy.json\"), \"w\") as f:
        json.dump(payload, f, indent=2)

def build_snippet(data, outdir):
    tpl = \"\"\"<!-- Autogenerated snippet for {sku} -->
<article class=\"product-card\">
  <img src=\"{thumbnail}\" alt=\"{title} thumbnail\" loading=\"lazy\" />
  <h3>{title}</h3>
  <p>{tagline}</p>
  <a href=\"#\" class=\"btn\">View on Gumroad</a>
  <a href=\"#\" class=\"btn\">View on Etsy</a>
</article>
\"\"\"
    os.makedirs(outdir, exist_ok=True)
    with open(os.path.join(outdir, f\"{data['sku']}.html\"), \"w\") as f:
        f.write(tpl.format(**data))

def main():
    for prod_folder in pathlib.Path(\"products\").iterdir():
        if not prod_folder.is_dir():
            continue
        with open(prod_folder / \"product.yml\", \"r\") as f:
            data = yaml.safe_load(f)
        build_gumroad(data, \"marketplaces/gumroad/dist\")
        build_etsy(data, \"marketplaces/etsy/dist\")
        build_snippet(data, \"website/snippets/dist\")
        print(f\"Built: {data['sku']}\")

if __name__ == \"__main__\":
    main()
